title: 向晓东
description: 天青色等烟雨，而我在等你。
show_downloads: false

baseurl: "/cayman-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://wjw875.github.io/wangjinwu.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

# theme: leave it empty

# social
author: wjw875
image: /thumbnail-jumbo.png
twitter:
  username: wjw875

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

# header_page_refs: ['now', 'about', 'contact']

theme: jekyll-theme-cayman-blog

gems:
  - jekyll-feed